services:
  invoice-generator:
    image: josephlteif/invoice-generator:latest
    container_name: invoice-generator
    ports:
      - "5001:5000"
    volumes:
      - invoice_db:/app/instance
      - invoices_files:/app/invoices
    environment:
      - FLASK_ENV=production
    restart: unless-stopped

volumes:
  invoice_db:
  invoices_files:
